version: '3'
services:
#MongoDB service 
    mongo_db:
     container_name: mongo_container
     image: mongo:latest
     volumes:
      - mongo_db:/data/db
     ports:
      - '27017:27017'

#Node API service       
    api:
      container_name: node_container
      restart: always
      build: .
      ports:
        - '8000:3000'
      environment:
        PORT: 3000
        MONGO_URL: mongodb://mongo_db:27017
        DB_NAME: my_db
        NAME: TrulyMittal
      depends_on:
        - mongo_db
volumes:
   mongo_db: {}
         
         